### ISSUE TITLE
Generated dfu.pyc not in GIT ignore list

### ISSUE THREAD

**Issue by esden** [1bitsquared/superbitrf-firmware#6]
[IMPROVEMENT] A git status ( after a make and then a pull) would give:

Untracked files:
...
scripts/dfu.pyc

originally submitted by @OpenUAS esden/superbitrf-firmware#8

**Comment by flixr** [comment]
Should be closed as it is fixed with 28d7178191e3b15c0113e533befa9fae51db6b81

**Comment by esden** [comment]
Thanks! :)
