### ISSUE TITLE
Flashin with BMP and USBRF both connected not possible

### ISSUE THREAD

**Issue by OpenUAS** [1bitsquared/superbitrf-firmware#8]
As a user working on my PC to improve PPRZ I like to be able to flash a Lisa(S) by use of a Blackmagicprobe and still leave the USBRF in my PC. Dozen times plugging and unplugging one and the other in an hour is really not a realistic working scenario.

**Comment by esden** [comment]
And why would you need to replug those? You only need to adjust your settings to use the correct tty ports for one or the other.

**Comment by OpenUAS** [comment]
Maybe my bad after frantic pluggin and repluggin of last hour, will re-test and close if not an issue.

**Comment by esden** [comment]
If you need to replug for other reason. Please describe in more detail your error and a detailed step by step description to reproduce the error, so we have a chance of fixing it. :)

**Comment by OpenUAS** [comment]
If iit work for you, no doubt it was a hickup at my side. Will not waste time on it atm. The real reason to have a smooth working environment was to stat with the debugging of the d@mn binding issue. Will come back to that. in another issue :) There I will file detailed issues.
